tap "railwaycat/emacsmacport"

brew "aspell"
brew "cmake"
brew "libtool"
brew "bat"
brew "eza"
brew "fish"
brew "fisher"
brew "fd"
brew "fzf"
brew "zoxide"
brew "gh"
brew "ghq"
brew "ripgrep"
brew "starship"
brew "mise"
brew "webp"
brew "railwaycat/emacsmacport/emacs-mac@29", args: ["with-modern-icon"]

cask "font-hack-nerd-font"
cask "claude-code"
cask "ghostty"
cask "keepassxc"
cask "keepingyouawake"
cask "chatgpt"
cask "miro"
cask "notion"
cask "obsidian"
cask "raycast"
